### ISSUE TITLE
package dependencies and launch file for topological navigation

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#106]
If you want to run topological navigation you need to have monitored navigation running. If you want to run monitored navigation running you need the human help manager (at least). These should be added as runtime dependencies of the packages.

**Comment by marc-hanheide** [comment]
assign @Jailander ?

**Comment by hawesie** [comment]
I also think human help manager should be moved into this repo if it's completely general purpose. I mentioned this in a comment to https://github.com/strands-project/strands_recovery_behaviours/issues/8

**Comment by lucasb-eyer** [comment]
`python-webpy` should also be added as a dependency, otherwise I get

```
[WARN] [WallTime: 1415723836.741276] Import error: No module named web
```

**edit:** I accidentally a "2".

**Comment by marc-hanheide** [comment]
there's no rosdep key for that is there? Please add it in https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/strands.yaml 

e.g.

```
python-webpy:
  ubuntu: [python-webpy]
```

with a pull request and then add it to the respective `package.xml`

**Comment by marc-hanheide** [comment]
follow up question: Is this a run_depend of strands_navigation or of monitored_navigation or of the recovery_behaviours, @BFALacerda ? Make sure you put it where it belongs!

**Comment by bfalacerda** [comment]
none of them. I think its strands_webserver.

**Comment by marc-hanheide** [comment]
Who is in charge of that one, then?

**Comment by bfalacerda** [comment]
@hawesie ?

**Comment by marc-hanheide** [comment]
I found the import in https://github.com/strands-project/strands_ui/blob/hydro-devel/strands_webserver/src/strands_webserver/page_utils.py so that confirms it should be in that `package.xml`, @hawesie ?

**Comment by marc-hanheide** [comment]
It is said in https://github.com/strands-project/strands_ui that it needs to be installed and that there is no rosdep key. So, let's add it and get over with it ;-)

**Comment by lucasb-eyer** [comment]
See strands-project/rosdistro#194

**Comment by hawesie** [comment]
Thanks @lucasb-eyer. I'll add the run deep to the web server. Sorry, I thought I'd done this ages ago!

**Comment by bfalacerda** [comment]
solved in https://github.com/strands-project/strands_navigation/pull/120
