### ISSUE TITLE
Recovery behaviours for non-strands users?

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#108]
Following on from https://github.com/strands-project/strands_recovery_behaviours/issues/8 are there any non-strands/scitos specific recovery behaviours that could be added to this repo to enable new users to work with monitored navigation?

**Comment by bfalacerda** [comment]
i can't think of anything that is that dependence-free, except allowing the user to pause and resume the navigation via a service call. pretty useless stuff...

**Comment by marc-hanheide** [comment]
what about a simple webhook strategy, e.g. one can configure an URL that the recovery behaviour POSTs json payload to and then waits some time to get a respond. That would allow people to write very simple web apps and still interact with the system. But no idea if anyone would use it...

**Comment by bfalacerda** [comment]
Your last sentence is the key point for me, I don't think anyone is going to use it. Also, if someone does decide to use it, they'll probably want to develop their own recovery behaviours anyway.

**Comment by hawesie** [comment]
Ok, let's drop this for now.
