### ISSUE TITLE
Add monitored nav node to topological navigation launch file

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#109]
As described in https://github.com/strands-project/strands_recovery_behaviours/issues/8 the topological nav launch file should also run 

```
rosrun monitored_navigation monitored_nav.py 
```

as it is required for any behaviour.

**Comment by bfalacerda** [comment]
I moved the launch file for the strands-specific monitored navigation [here](https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_recovery_behaviours/launch/strands_monitored_nav.launch). I think we should just add the monitored_navigation node to the topological_navigation launch file, so it is robot independent, but we should also have some kind of strands nav launch that launches our complete monitored nav state machine. Where would that go?

**Comment by hawesie** [comment]
In the recovery behaviours repo somewhere?

**Comment by bfalacerda** [comment]
after finding out that we have strands specific launch files in scitos_robot, i edited everything so that topological_navigation.launch has an argument for the monitored nav config file. By default it's null (bare-bone monitored nav), and then its set to our config file in strands_navigation.launch. See https://github.com/strands-project/strands_navigation/pull/120 and https://github.com/strands-project/scitos_robot/pull/65

**Comment by hawesie** [comment]
But we shouldn't have strands-specific stuff in the scitos repo should we? @marc-hanheide 

Otherwise what you've done sounds good.

**Comment by marc-hanheide** [comment]
What defines strands-specific? Of course it is strands specific, but it shouldn't be robot or site specific?!

**Comment by hawesie** [comment]
My (perhaps implicit) understanding is that anything with the `scitos` prefix should be able to run on a scitos platform without extra strands stuff. So we should move all of the `strands`-prefixed stuff from https://github.com/strands-project/scitos_robot/tree/hydro-devel/scitos_bringup/launch for example.

**Comment by marc-hanheide** [comment]
You mean move all the strands stuff somewhere else? OK, where?

**Comment by hawesie** [comment]
a strands_bringup package under strands_systems?

**Comment by marc-hanheide** [comment]
OK, can do. My understanding is that the robot-specific files should be removed from strands_systems, right? All the strands_{bob,linda,...} packages. I suggest to create a `deprecated` branch from the current one, then remove all those specific packages, create a new `strands_bringup` and release that. I want to hear from @Jailander, @cdondrup and @BFALacerda what they think about this. It seems that it will cause quite some changes in other packages that currently have `scitos_bringup` in them, but it seems to make sense.

**Comment by marc-hanheide** [comment]
Or, alternatively, create a dedicated `strands_bringup` repository with just the new package itself in it. That might well be the cleaner solution.

**Comment by Jailander** [comment]
I agree with creating a strands_bringup package this way we can have both robot and simulation launch files, however I don't see why we have to delete the robot specific packages, the are useful not only for launch files for example we also have the robot attributes file there.

**Comment by hawesie** [comment]
There are at least two reasons to deprecate existing robot-specific files:

1) To prevent confusion with people launching the wrong things
2) To encourage people to collaborate on a single set of well-documented robust launch files for our common systems.

We should then have site-specific parts which only include site-specific details.

**Comment by marc-hanheide** [comment]
because we don't want to release them, as they are _very_ specific to our sites. It will confuse people if they are released, I believe. If we want to keep them (which we might), it will be the better option to create new repo. But I believe we should definitely move away from those specific files. They stop people from providing and using generic launch files!

**Comment by bfalacerda** [comment]
I like `strands_bringup` in `strands_systems`. Why would other packages have `scitos_bringup`in them? As i understand it, these will be core launch files that should always be launched to get the system running. Hence, the launch file in other packages should _not_ be launching anything from bringup themselves.

Regarding the robot specific files, if we keep them (I have no opinion on if they're worth it), those are the ones that should be moved to a non-release repo.

**Comment by Jailander** [comment]
Right now these "robot specific" files are just to set the parameters of the main files that as we have disscussed today in gitter everyone is using. 

I agree with not releasing this repo as it is only for our configurations, I also don't see any rush on deleting it as it is useful right now.

**Comment by marc-hanheide** [comment]
:+1: for @BFALacerda

**Comment by marc-hanheide** [comment]
Which ones is everybody using @Jailander ? If there _is_ an agreed set of launch files that _everybody_ is using, then we should release those. I think we have to release them if hey form the basis of our marathon system. I presume, people are not using `strands_linda` or at least they shouldn't.

**Comment by Jailander** [comment]
of course there is, https://github.com/strands-project/scitos_robot/tree/hydro-devel/scitos_bringup the Readme explains how the launch files are being organised, as far as I know they are being used in Lincoln, Aachen, KTH and Bham. the "robot specific" files are just for setting the parameters as the Readme states

**Comment by hawesie** [comment]
That README is great, but it should be in strands_bringup as should the strands launch files.

**Comment by Jailander** [comment]
yes as I said, I see no problem with it, I can move them as soon as I know in which repo should this package go

**Comment by marc-hanheide** [comment]
So, what about:
- moving the strands_linda stuff into our own Linda dump: https://github.com/LCAS/linda
- moving the other `strands_<ROBOT>` packages to a deprecated branch
- move the README and the strands-specific launch files (everything that is going beyond launching the scitos robot) to strands_systems and create a strands_bringup with them (including the great README)?

**Comment by hawesie** [comment]
:+1:

**Comment by bfalacerda** [comment]
:+1:

**Comment by bfalacerda** [comment]
or just create a new repo in our github and shove them in there

**Comment by marc-hanheide** [comment]
No, I don't want any more repos ;-) And that would mean a lot of subtree export/import. A branch doesn't hurt, does it?

**Comment by Jailander** [comment]
Ok I can do that, however @nilsbore @ToMadoRe  will need to be warned about their repos being moved to a deprecated branch, so they can also find a place for them. Also @BFALacerda you have a repo there but I think you don't have launch files for the parameters.

@hawesie or @marc-hanheide can you create the deprecated branch on https://github.com/strands-project/strands_systems as I am not an admin there.

**Comment by marc-hanheide** [comment]
created the branch just now... feel free to `git rm` in `hydro-devel`: https://github.com/strands-project/strands_systems/tree/deprecated

**Comment by Jailander** [comment]
Ok thank you!! will do it tomorrow morning as I am on the phone as you can tell by the speed of my replies.

**Comment by marc-hanheide** [comment]
Cheers :beers:

**Comment by bfalacerda** [comment]
@Jailander  the bob branch is pretty much useless with the new launch files. if we end up needing something from it i'll grab it later

**Comment by marc-hanheide** [comment]
I'll close this as there is now https://github.com/strands-project/strands_systems/issues/47 to continue this.

**Comment by Jailander** [comment]
OK to Both

**Comment by ToMadoRe** [comment]
@Jailander: What repo do you mean? I can't even remember having changed any code related to `strands_navigation`. So probably not a problem for me.

**Comment by Jailander** [comment]
@ToMadoRe is about this repo https://github.com/strands-project/strands_systems/tree/hydro-devel/strands_werner that was created when @cdondrup was there check new issue. you will need to do something about it when you setup the new launch files
