### ISSUE TITLE
Not turning on the spot.

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_navigation#127]
We have small corridors. Often, it would be really necessary for Karl when he's on a topological node to turn on the spot and then start moving. He doesn't want to do that, he always wants to turn+drive forward, which fails because there's not enough space.

Is this intended? Where can I debug and tune it?

**Comment by gestom** [comment]
We tried to play with the DWA planner params and setting the "min_trans_vel to 0.001" and "forward_point_distance to 0.1" (via rosservice call /move_base/DWAPlannerROS/set_parameters) seemed to help in cases when the robot had to turn prior to moving. Try it as well and let me know.

**Comment by bfalacerda** [comment]
https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/strands_movebase_params/dwa_planner_ros.yaml#L30

These are not the most recent parameters. We changed it back to the defaults around the g4s deployment. Probbabliy they got lost with this moving files around...

He turns much more in place when you put these (line 30 and 31) to default.

I dont have time to look into this now, but you can check the commit history in scitos_2d_navigation and look for the correct file

**Comment by lucasb-eyer** [comment]
On a first impression, changing `min_trans_vel` to `0.001` seems to be enough. `forward_point_distance` to `0.1` would be inside the robot! (we measured), why'd you set it that way?

Will also have a look and try out @BFALacerda's mentioned parameters.

**Comment by bfalacerda** [comment]
@lucasb-eyer it looks like we didnt merge our g4s params upstream. Here is the dwa planner config file that we were using:

https://github.com/BFALacerda/scitos_2d_navigation/blob/with_back/scitos_move_base_params_3d/dwa_planner_ros.yaml

Maybe increasing the sim_time param a bit improves things a bit also. Then, we also discussed the costmap params a bit last year, mainly the footprint - see https://github.com/strands-project/autonomous_patrolling/issues/70
. @AlexanderHermans used this footprint which seemed to improve things:

footprint: [[-0.3000,   -0.3200],[   -0.5200,   -0.1100],[   -0.5200,
0.1100],[   -0.3000,    0.3200],[    0.1000,    0.3200],[    0.2500,
0.1100],[    0.2500,   -0.1100],[    0.1000,   -0.3200]]

The version we're using still has the rectangle footprint being used.

**Comment by bfalacerda** [comment]
@nilsbore now there are move_base configs in two repos:

https://github.com/strands-project/strands_movebase/tree/hydro-devel/strands_movebase/strands_movebase_params

https://github.com/strands-project/scitos_2d_navigation/tree/hydro-devel/scitos_move_base_params

I'm assuming we're using the ones in strands_movebase. Whats the scitos_2d_nav repo for then, for people that want to use our configs on a scitos without chest cam?

**Comment by lucasb-eyer** [comment]
I took the time to create and test a much more precise footprint (edit: it also takes care of the screen), which improves navigation quite a bit.

It'd be nice if some of you could also try it out, and if it works, we could use it as a default? Or at least make it a parameter to the launchfile:

``` yaml
footprint: [[-0.30,-0.32], # Back side right
            [-0.52,-0.11], # Back right
            [-0.52, 0.11], # Back left
            [-0.30, 0.32], # Back side left
            [-0.05, 0.31], # Front side left
            [ 0.05, 0.25], # Thick front left
            [ 0.15, 0.13], # Thin front left
            [ 0.20, 0.00], # Front
            [ 0.15,-0.13], # Thin front right
            [ 0.05,-0.25], # Thick front right
            [-0.05,-0.31]] # Front side right
```

I'm still playing with the other parameters you guys have pointed me to.

**Comment by bfalacerda** [comment]
this looks good. i'll try it. You don't have problems with the local planner missing the rate (200ms i think) because of the footprint being more accurate?

**Comment by lucasb-eyer** [comment]
Didn't encounter it yet, but as you know from this morning, I didn't get to see `move_base` output yet...

**Comment by bfalacerda** [comment]
_comment was in wrong place_

**Comment by lucasb-eyer** [comment]
You sure your last message is in the right issue, and wasn't supposed to be in #137?

**Comment by bfalacerda** [comment]
closing, more discussion in https://github.com/strands-project/strands_movebase/issues/27
