### ISSUE TITLE
Reimplement navigation node as policy executor

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#129]
Ignore until after the marathon ;)

Given that policy execution seems to be the future of executing topological navigation actions, we should update the current navigation node to work as an policy executor, e.g. using search to create a policy for the goal it is given. This could be a nice student/intern project.

**Comment by Jailander** [comment]
That node already exists here https://github.com/strands-project/strands_navigation/blob/hydro-devel/topological_navigation/scripts/execute_policy_server.py and was tested toroughly when @BFALacerda came to Lincoln.

**Comment by bfalacerda** [comment]
yes @Jailander , what I think @hawesie means is that we don't have a simple policy generator that doesn't use PRISM, and that's not released yet.

If we find  someone (a student) to implement a simple value iteration thingy to generate the policies it doesn't hurt, but I'll be getting the whole mdp/PRISM stuff released soon, so I prefer to focus on that.

**Comment by Jailander** [comment]
Ok, since I read policy_executor I got confused, I could take a look into it but I can't promise anything with all the Marathon stuff

**Comment by bfalacerda** [comment]
see first line of @hawesie's comment ;)

**Comment by Jailander** [comment]
hahaha, Ok point for you :P

**Comment by Jailander** [comment]
Hi @bfalacerda did you ever get around to do this? it would be useful for the movebase testing things, if not we can work around it but if you have it, we could use it

**Comment by bfalacerda** [comment]
i don't have it... we could use the sequential plans topo nav generates and turn them into the policy message type instead

**Comment by Jailander** [comment]
yes not a problem, just asking, I think I can sort it out like you said

**Comment by bfalacerda** [comment]
thanks! :)

**Comment by Jailander** [comment]
Second Commit in #273 Does something similar to this, maybe we can close the issue before it hits its one year birthday

**Comment by Jailander** [comment]
`rosrun topological_navigation get_simple_policy.py` does this, I'll close reopen if necessary.
