### ISSUE TITLE
Metapackage does not define run_depends

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_navigation#130]
The metapackage `strands_navigation` is currently not defining any run_depends which makes it useless. Since `strands_base` depends on it, it should contain all the packages in here.

This leads to things like descriptions that use `topological_utils` but this is not installed by default.

**Comment by cdondrup** [comment]
Closed via #130.

**Comment by Jailander** [comment]
via #131 #130 is the issue itself :P

**Comment by cdondrup** [comment]
Mea culpa
