### ISSUE TITLE
topological nav should not depend on scitos_msgs

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#136]
I see the dependeny on the package.xml https://github.com/strands-project/strands_navigation/blob/hydro-devel/topological_navigation/package.xml#L22 but I don't really know where it's needed, I'm guessing it's some old thing that just stayed in there.

Anyway, we shouldn't have strands_navigation depending on it, so it needs to be removed

**Comment by marc-hanheide** [comment]
I don't know either. Feel free to remove and see if it still works

**Comment by Jailander** [comment]
yes I'll fix it in a bit that dependency existed in old versions and stayed there

**Comment by Jailander** [comment]
Closed via #143
