### ISSUE TITLE
stop planning for exact poses in intermediate waypoints

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#167]
for most of the intermediate nodes (door passing or docking nodes for example are a bit of an exception), topological navigation should be planning to go to areas of the environment, i.e., influence areas of nodes, and not to exact poses. How to do this using the move_base framework is still something we need to look at. One way to do it might be dynamically reconfiguring the move base goal error params, but we have to check how the global planner behaves when we give it very coarse goals.

I suggest extending the topological map definition, and have the edges labelled with the action plus information on how accurately we need to be positioned before starting to execute it.

**Comment by Jailander** [comment]
Hi, yes I agree with this but we had talked about adding extra tolerance information to the nodes not the edges, I am working on this, I didn't push before as it meant a huge change on the system and I thought it would be very risky to do right before the marathon. I will have it done by the end of the week along with #169 and #168 

Just a general warning from the end of the week the topological map definition will change and all (ros) nodes need to use the published map and not the ones stored in the mongodb I think this will affect @hawesie 's stuff

**Comment by bfalacerda** [comment]
great! :)
can you give an example on how the new topological node will look like?
 What's the "use published map" change?

**Comment by Jailander** [comment]
Yes the main difference is that maps will be stored as the whole topological map not node by node as it was being stored in the mongodb, so now the mongodb query has to be for the map and not for the list of nodes. This will allow us to "undo" changes when editing topological maps among other things.

the new msg format so far is this (any further ideas are welcomed [this week]):
- **Topological map**:

``` yaml
string name
string location
string pointset
string last_updated
strands_navigation_msgs/TopologicalNode[] nodes
```
- **Topological node**:

``` yaml
string name
string map
string pointset
geometry_msgs/Pose pose
float64 yaw_tolerance    #The tolerance in radians for the waypoint position
float64 xy_goal_tolerance #The tolerance in meters for the waypoint position
Vertex[] verts
Edge[] edges
```
- **Edges**:

``` yaml
string edge_id
string node
string action
float64 top_vel
string metric_map
```

**Comment by RaresAmbrus** [comment]
@Jailander what does the `string metric_map` do in the edges message?

**Comment by Jailander** [comment]
is the 2D map that should be used when traversing each edge, the thing is that for example in places where there are different floor you may want to change the map you are navigating with, for example when you take the lift to another floor you want to switch maps to that floor, maybe I should change the name to 2d map :/

**Comment by RaresAmbrus** [comment]
Ah ok, switching between maps depending on various conditions makes sense, but I think a different name might be good, otherwise it might create confusion with the 3D maps we've already dubbed "metric_maps"

**Comment by Jailander** [comment]
yes I will :)

**Comment by RaresAmbrus** [comment]
Great, thanks :)

**Comment by bfalacerda** [comment]
One issue that i see is that we'll have different requirements on final poses, taking into account the edges: we might have a node with a door passing edge and a move base edge. For door passing, we really need the robot to get into a more accurate pose before starting. For move base, we're happy to send the new goal immediately after the robot gets into the node's influence area. So, I think it would be better having the pose accuracy params in the edge definition, instead of the nodes definition.

Also, I think that for most of our nodes, we don't really need a polygon, we can just use distance to the waypoint. That would make the calculation of closest_node much easier, and would also allow us to edit influence areas more easily: we just need to change a radius. We can keep the polygon stuff for special cases, but i think in general everything becomes easier if we just have a  waypoint radius param

**Comment by bfalacerda** [comment]
also, the `map`param in node seems to be doing the same as the `metric_map` in edge. In this case i think its enough having nodes associated to different 2d maps, and the edges dont need it

**Comment by Jailander** [comment]
yes the map param in the nodes was an old one, I was using the one in the edges, but I will try using only the one in the nodes then.

about the goal tolerance, I'm not sure we need that right now with move_base the robot follows to the next edge as it enters the influence zone, with other actions it goes to the waypoint, the goal tolerance we talked about was more in terms of navigating to places that might be obstructed.

about the influence area there is not big difference between a polygon and a circular influence area, as I only check if its inside the polygon when its within the maximum radius of the polygon and is not computationally heavy, I will modify the way we edit the influence area to make it easier and I'll try to add circular zones too.

**Comment by bfalacerda** [comment]
the thing is that sometimes we  have the robot not reaching the influence area because the exact pose is blocked, even though it's just an intermediate node that we just want to get close to and then continue.
I think that by associating a goal tolerance to each edge, which needs to be achieved before triggering the action labelling that edge, we get some more flexibility. The default goal tolerance can be equal to the influence area, but then we can play with that in certain cases

The influence area radius thingy is not a huge issue then, as you're calculating it in a smarter way than i would :) anyway in terms of usability, it would be good to be able to set a single parameter for that

**Comment by Jailander** [comment]
Yes I am struggling with the planning to optional poses when local planner fails, maybe it makes sense to have goal tolerance linked to actions rather than nodes or edges, that change can be made easily; however we still have the issue of navigating to exact poses when that is the final node. Like approaching a desk.
About the influence zones that is the idea, I am thinking about it ;)

**Comment by bfalacerda** [comment]
if it's the final node there's no other nav actions to be executed so we send the robot to the exact pose by default?

**Comment by Jailander** [comment]
yes but then it fails when the pose is blocked

**Comment by bfalacerda** [comment]
we can add a goal tolerance for the actions to be executed in waypoints also i guess, but for now i dont see failing then a huge problem. what is more pressing is getting rid of failures on intermediate waypoints

**Comment by Jailander** [comment]
yes hence the tolerance in the nodes, for intermediate waypoints we can use the tolerance linked to actions and maybe use the influence area as tolerance for move_base actions, does this sound logical?

**Comment by bfalacerda** [comment]
not sure if i understand what you mean, can you re-explain?

**Comment by Jailander** [comment]
yes I'm just saying that we can have standard tolerances for each action (instead of assigning them to the edges) that can be parameters, and leave the tolerance in the node definition that will be used when that node is the final destination.

**Comment by bfalacerda** [comment]
but then if there's two different actions you can do at one node, one that needs an accurate pose, and another that doesn't, you cant tell them apart.

Regarding tolerances on edges vs tolerances as params, I like it on the edges because it just sounds more flexible to me. You can even have different requirements for the same action, depending on the edge you're going to transverse. However, TBH I don't see a case where we can need something like that right now, so if you think the overhead of doing it is too much, params should do the trick also

**Comment by Jailander** [comment]
no the problem is not the effort of doing it is practically the same, the only problem is that I don't know if adding too many parameters to the edges will make the topological map more complicated to setup, and we need to find a proper way of editing all these things, but I can do it either way. I'll just add it to the nodes and find a way to ease the map edition

**Comment by bfalacerda** [comment]
yeah, i'd say default is always exactly the same as the influence area of the node. then we edit that. we can even have some scripts for our special actions that do the changes automatically

**Comment by Jailander** [comment]
yes I'll play with it a little and see what I can do to make it easy to edit

**Comment by bfalacerda** [comment]
@Jailander any news on this? I'd like to test my mdp stuff using the new topological maps

**Comment by Jailander** [comment]
hey @bfalacerda I'm on holidays right now I wanted to test it before I left but it was impossible, I will change some stuff today and test it tonight (GMT -5) so you can have it tomorrow, I couldn't do it before as I was travelling

**Comment by Jailander** [comment]
I think this is done now reopen if I missed something

**Comment by bfalacerda** [comment]
it's not done, but it's pretty much #187 so we can leave it closed
