### ISSUE TITLE
have edges in topological map labelled with top speed allowed

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#168]
During our library deployment, we found out that 0.55 is just too fast to cope with crowded environments. I think we should extend the topological map definition, and add information on the top speed we allow for at least move_base edges. We can then dynamically reconfigure move_base before executing the action

**Comment by Jailander** [comment]
On it see other issues

**Comment by bfalacerda** [comment]
closing old solved issues
