### ISSUE TITLE
extend topological map definition

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#169]
It might be interesting to add some more info to the edges in our topological maps. see https://github.com/strands-project/strands_navigation/issues/167 and https://github.com/strands-project/strands_navigation/issues/168

**Comment by Jailander** [comment]
yes this is work in progress, I will also add map information to the edges so we can switch maps when traversing edges, Also a label will be added for cost estimation and to be able to connect nodes with more than one edge.

**Comment by bfalacerda** [comment]
closing old solved issues
