### ISSUE TITLE
update to use ros_datacentre

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#17]
this repo is not using the new ros_datacentre. The interactions with the db should be updated, as in https://github.com/strands-project/autonomous_patrolling/blob/hydro-devel/waypoint_recorder/scripts/insert_in_db.py and https://github.com/strands-project/autonomous_patrolling/blob/hydro-devel/waypoint_patroller/src/waypoint_patroller/patroller.py

@Jailander do you have time to do this? I can't really test the topological navigation until it is done, so if you don't  have time I can look into it.

**Comment by Jailander** [comment]
Hi,

I can do it tomorrow morning very early, I can't do it today, however, you don't need those repos for the topological navigation, BUT you will need this one: https://github.com/strands-project/strands_navigation/tree/hydro-devel/topological_utils which also needs some adapting to the new datacentre that shouldn't be too hard, but if you prefer I can do it tomorrow morning.

**Comment by bfalacerda** [comment]
yeah, those are just examples of updated files that read from and write to the ros_datacentre using the new  MessageStoreProxy class. I think that not only topological_utils, but also the  topological navigation needs to be updated to use it.

**Comment by Jailander** [comment]
yes sorry I read you email wrong how embarrassing, I tested the topological_navigation as it stands now, using the ros_datacentre and it works, I will of course update it using the new class, but you test it like it is right now if you want.

**Comment by bfalacerda** [comment]
I tried to edit https://github.com/strands-project/strands_navigation/blob/hydro-devel/topological_utils/scripts/insert_map.py to add waypoints using the MessageStoreProxy, but it's a bit less straightforward than I thought. It looks like the meta information needs to be pairs of strings, and you have stuff like 

```
'edges': [{'node': 'WayPoint1', 'action': 'move_base'}, {'node': 'WayPoint2', 'action': 'move_base'}, {'node': 'WayPoint3', 'action': 'move_base'}, {'node': 'WayPoint4', 'action': 'move_base'}, {'node': 'WayPoint5', 'action': 'move_base'}]
```

This gives the following error when you try torun the add metthod from MessageStoreProxy:

```
Traceback (most recent call last):
  File "/home/bruno/devel_ws/src/strands_navigation/topological_utils/scripts/insert_map.py", line 136, in <module>
    msg_store.insert(p,val)
  File "/opt/strands/strands_ws/src/ros_datacentre/ros_datacentre/src/ros_datacentre/message_store.py", line 30, in insert
    self.insert_srv(self.database, self.collection, serialised_msg, meta_tuple)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 605, in send_message
    serialize_message(self.write_buff, seq, msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/strands/strands_ws/devel/lib/python2.7/dist-packages/ros_datacentre_msgs/srv/_MongoInsertMsg.py", line 134, in serialize
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 316, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 238, in check_type
    check_type(field_name+"[]", base_type, v)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 248, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 214, in check_type
    raise SerializationError('field %s must be of type str'%field_name)
genpy.message.SerializationError: field meta[].second must be of type str
```

@hawesie , is the add method supposed to just accept meta information only in the form of pairs of strings? If so, how should we tackle this kind of info?

@Jailander , i pushed what I added to the branch not_working of my fork in case you want to take a look at it.

**Comment by hawesie** [comment]
It looks like that stuff above should be in a message type rather than provided as meta-information as it doesn't look descriptive of some data rather more like data itself.

That said I need to do a little more work on the code. I have a way for python code to add in arbitrary meta-information, but it is less easy to retrieve. Rewriting to not use a ROS service, but to use pymongo or the C++ driver instead, can fix this.

**Comment by Jailander** [comment]
Hi,

@BFALacerda I am NOT proud of this, but I just did a very small hack that seems to work for now, I kept the old functions and just changed strands_datacentre to ros_datacentre, I just tried this and it works.

I will switch everything to work using our new interfaces and I hope it doesn't take long, but meanwhile you can test the topological navigation using this horrible hack, I pushed this solution to my fork https://github.com/Jailander/strands_navigation.

**Comment by bfalacerda** [comment]
Cool, I should have tried that before trying to change the rest. Thanks!

**Comment by bfalacerda** [comment]
I tried it but it looks like the topological map is not being added correctly. I first run

```
rosrun topological_utils insert_map.py output_file.txt full_bham_cs cs_lg
```

and I see a connection to the datacentre happening. However, when I run 

```
 roslaunch topological_navigation topological_navigation.launch map:=full_bham_cs node_by_node:=false
```

I get the following:

```
false
[ERROR] [WallTime: 1393936252.417002] Desired pointset 'full_bham_cs' not in datacentre
[ERROR] [WallTime: 1393936252.417211] Available pointsets: [u'waypoint_set1', u'full_bham_lg']
Traceback (most recent call last):
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/localisation.py", line 133, in <module>
    server = TopologicalNavLoc(rospy.get_name(),filename)
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/localisation.py", line 38, in __init__
    self.lnodes = self.loadMap(filename)
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/localisation.py", line 87, in loadMap
    raise Exception("Can't find waypoints.")      
Exception: Can't find waypoints.
[INFO] [WallTime: 1393936252.482261] Loading file from map full_bham_cs
Using datacentre   bruno-dell : 62345
[ERROR] [WallTime: 1393936252.484995] Desired pointset 'full_bham_cs' not in datacentre
[ERROR] [WallTime: 1393936252.485149] Available pointsets: [u'waypoint_set1', u'full_bham_lg']
Traceback (most recent call last):
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/navigation.py", line 299, in <module>
    server = TopologicalNavServer(rospy.get_name(),filename,mode)
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/navigation.py", line 39, in __init__
    self.lnodes = self.loadMap(filename)
  File "/home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/navigation.py", line 270, in loadMap
    raise Exception("Can't find waypoints.")
Exception: Can't find waypoints.
[topological_localisation-1] process has died [pid 10235, exit code 1, cmd /home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/localisation.py full_bham_cs __name:=topological_localisation __log:=/home/bruno/.ros/log/e7cbd0a2-a396-11e3-95a2-f01faf28c9e3/topological_localisation-1.log].
log file: /home/bruno/.ros/log/e7cbd0a2-a396-11e3-95a2-f01faf28c9e3/topological_localisation-1*.log
[topological_navigation-2] process has died [pid 10236, exit code 1, cmd /home/bruno/devel_ws/src/strands_navigation/topological_navigation/scripts/navigation.py full_bham_cs false __name:=topological_navigation __log:=/home/bruno/.ros/log/e7cbd0a2-a396-11e3-95a2-f01faf28c9e3/topological_navigation-2.log].
log file: /home/bruno/.ros/log/e7cbd0a2-a396-11e3-95a2-f01faf28c9e3/topological_navigation-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
```

The pointsets in there are the ones I added using the insert script in waypoint_recorder. Did I do anything wrong?

**Comment by Jailander** [comment]
I don't think so, can you check with robomongo or something similar if the map is there? if the insert_map script worked it should be in the autonomous_patrolling DB in the waypoint collection.

silly question, did you run the tmap_from_waypoints.py script too?

**Comment by Jailander** [comment]
When you run the insert_map script you should see some JSON like output on the screen like this:

```
{'map': 'bla2', 'name': 'ChargingPoint', 'vertices': [(1.38, 0.574), (0.574, 1.38), (-0.574, 1.38), (-1.38, 0.574), (-1.38, -0.574), (-0.574, -1.38), (0.574, -1.38), (1.38, -0.574)], 'pointset': 'small2', 'edges': [{'node': 'WayPoint1', 'action': 'move_base'}, {'node': 'WayPoint2', 'action': 'move_base'}], 'waypoint': ['-2.3003', '0.120533', '-4.88295e-05', '0', '0', '-0.0530802', '0.99859']}
{'map': 'bla2', 'name': 'WayPoint1', 'vertices': [(1.38, 0.574), (0.574, 1.38), (-0.574, 1.38), (-1.38, 0.574), (-1.38, -0.574), (-0.574, -1.38), (0.574, -1.38), (1.38, -0.574)], 'pointset': 'small2', 'edges': [{'node': 'ChargingPoint', 'action': 'move_base'}, {'node': 'WayPoint2', 'action': 'move_base'}], 'waypoint': ['-7.95369', '-3.03503', '-4.4791e-05', '0', '0', '0.928319', '-0.371784']}
{'map': 'bla2', 'name': 'WayPoint2', 'vertices': [(1.38, 0.574), (0.574, 1.38), (-0.574, 1.38), (-1.38, 0.574), (-1.38, -0.574), (-0.574, -1.38), (0.574, -1.38), (1.38, -0.574)], 'pointset': 'small2', 'edges': [{'node': 'ChargingPoint', 'action': 'move_base'}, {'node': 'WayPoint1', 'action': 'move_base'}], 'waypoint': ['-8.91935', '2.94528', '0.00139425', '0', '0', '0.473654', '0.880711']}
```

can you see it??

**Comment by bfalacerda** [comment]
yes, it was being added, but the lines

```
        available = points_db.find().distinct("meta.pointset")
```

need to be replaced with

```
        available = points_db.find().distinct("_meta.pointset")
```

**Comment by Jailander** [comment]
hmmm, that doesn't happen to me, maybe I need to update my installation, is the navigation working now?

**Comment by bfalacerda** [comment]
maybe you'r trying to load a pointset that you added previously? it's launching, I'll see iftherobot moves after the integration meeting

**Comment by Jailander** [comment]
Yes I didn't realise that was the problem, thank you!

**Comment by bfalacerda** [comment]
everything (including the topological patroller) seems to work, if you change all the occurrences of "meta" by "_meta". From what I understand, once you start using the MessageStoreProxy, the references to "meta" will work again, so I won't push anything

**Comment by Jailander** [comment]
Yes, I wil switch to MessageStoreProxy tomorrow. 
Have you seen the statistics? are they fine like this?

**Comment by bfalacerda** [comment]
I think so, for now it's good

**Comment by Jailander** [comment]
cool!, one last question, did you try both modes for the navigation? (the node_by_node flag set to true/false)

**Comment by bfalacerda** [comment]
yes, both were ok

**Comment by hawesie** [comment]
This now appears to be done, reopen if not.
