### ISSUE TITLE
local_planner does not respect no-go costmap

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#177]
but it definitely should (also to prevent it going down the stairs ;-) )

**Comment by nilsbore** [comment]
AFAIK this is not totally straightforward with the current approach. I'll try to figure something out. (In the meantime, everyone use the chest camera!)

**Comment by marc-hanheide** [comment]
can't we just enable it in https://github.com/strands-project/strands_movebase/tree/hydro-devel/strands_movebase/strands_movebase_params ? It currently is enabled in https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/strands_movebase_params/global_costmap_params.yaml but not in https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/strands_movebase_params/local_costmap_params.yaml

**Comment by nilsbore** [comment]
That's the first thing that I'm gonna investigate, I'm not sure if it works like that.

**Comment by bfalacerda** [comment]
no, right now local costmaps dont support static layers. There's a ticket for it in the nav stack github but it doesnt really look to be anyone's priority

**Comment by bfalacerda** [comment]
some info on this is here:

https://github.com/strands-project/strands_movebase/issues/27

**Comment by mzillich** [comment]
actually I think we should stop at stairs using a lower level mechanism. e.g. continuously detecting drivable ground and sending a ping. a watchdog stops the robot immediately as soon as a ping is missed.

**Comment by hawesie** [comment]
We need all these things. Christian R is looking the lower level mechanism.

**Comment by mzillich** [comment]
@nilsbore Where is the cliff detection happening now?

**Comment by nilsbore** [comment]
@mzillich  Again, I want to clarify that the cliff detection (or 3d obstacle avoidance) was not running on Lucie when she fell and it has been working well when I've tested it. It is part of the general obstacle avoidance stuff and is done by finding points which are below the floor and raytracing them back to add virtual obstacles. The virtual cloud is generated here: https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/src/mirror_floor_points.cpp and added to the local costmap in this parameter file: https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/strands_movebase_params/costmap_common_params.yaml

**Comment by mzillich** [comment]
Sure, I knew it was not active. We also tested it in our hallways and it worked just fine. I just wanted to understand as much as possible how precisely it works and how it feeds into the system - which I now do :)  cheers

**Comment by nilsbore** [comment]
Yeah, it would make me also feel better if we have multiple mechanisms for this. This incident shows that it's needed. I also think it would be good to always run the chest camera on the main PC so that the network does not mess up transmission of point clouds.

**Comment by hawesie** [comment]
I thought that was the usual approach.

**Comment by Jailander** [comment]
not on every robot Lucie had the head camera on the main PC, and Linda runs all the 3D navigation stuff on the left cortex which is much quicker as we have the right cortex for the head camera, the launch files are setup in a way on which we try to reduce as mcuh the network traffic.

**Comment by Jailander** [comment]
@marc-hanheide @nilsbore @hawesie @bfalacerda can I close this considering that we no longer use no go maps and we have other mechanisms now like the no go nodes?

**Comment by marc-hanheide** [comment]
:+1:

**Comment by nilsbore** [comment]
Sounds good.
