### ISSUE TITLE
clearing cost map on new goal

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#178]
We thought that it might be useful to clear the obstacle map when new goals are being issued as a simple and effective means to avoid being stuck... Good idea? @Jailander @nilsbore @bfalacerda ?

**Comment by bfalacerda** [comment]
i don't think its needed, I got the clear costmap recoveries working (our config was wrong), so now move_base always clears them before failing anyway

**Comment by marc-hanheide** [comment]
I, so I close this.
