### ISSUE TITLE
allow dynamic re-configurable recovery behaviours

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#179]
We have discussed that it would be useful to enable/disable recovery behaviours on the fly (dynamic_reconfigure) as different tasks might have different constraints. E.g. for some tasks, we want the robot to fail more easily and feed this back to the planner (e.g. when it is just patrolling), and in some we want it to be extra insisting, e.g. when guiding a person. Please, can we discuss this, @hawesie @bfalacerda @Jailander ?

**Comment by nilsbore** [comment]
I did something similar for the walking group. You can do this via a service call right now, but you need to create your own state machine. See https://github.com/strands-project/strands_recovery_behaviours/tree/hydro-devel/walking_group_recovery for an example.

**Comment by marc-hanheide** [comment]
The SMASH stuff is just beyond me. What does this do?

**Comment by bfalacerda** [comment]
we dont have dynamic reconfigure, but you can change recovery behaviours on the fly by using service calls: 
https://github.com/strands-project/strands_navigation/blob/hydro-devel/monitored_navigation/README.md

This does require you to implement your own recovery behaviours as smach state machines though, given the whole smach implementation  of monitored_navigation, I don't see how you can do it any other way. My hope is that we dont need to define too many different situations. More info on how to do this is on the README also

**Comment by marc-hanheide** [comment]
OK, so it's again me not knowing all the cool features you've done ;-)
