### ISSUE TITLE
simple wait recovery behaviour

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#180]
we thought a recovery behaviour that just wait for either some time, or until now persons are being seen in a certain range to the robot anymore would make a lot of sense. What do people like @bfalacerda @cdondrup and @hawesie think about this?

**Comment by hawesie** [comment]
I think it makes sense, and might also be useful in G4S for narrow corridors.

**Comment by bfalacerda** [comment]
that's already in (the wait, not the people detection): 

https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_monitored_nav_states/src/strands_monitored_nav_states/recover_nav_states.py#L19

https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_monitored_nav_states/src/strands_monitored_nav_states/recover_nav.py#L22

**Comment by marc-hanheide** [comment]
Oh man... I'm impressed ;-)
