### ISSUE TITLE
New definitions for topological map

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#181]
@Jailander @marc-hanheide what's the status of the new definitions of the topological map? We need them before the MDP executor can be released https://github.com/strands-project/strands_executive/issues/129 and we need to test everything very well before the deployments this year.

**Comment by hawesie** [comment]
Please can these get merged this week? We have a lot of work to do which relies on this.

**Comment by marc-hanheide** [comment]
@Jailander is anything else needed? I'd like to get this finished, too, before we embark on the next integration round.

**Comment by Jailander** [comment]
yes, @bfalacerda and I are going to have a skype meeting to get this done, as there are still some things that need clarification on the msg definition and we don't want to keep changing msgs definitions constantly

**Comment by bfalacerda** [comment]
I'd like a pr with the current definition at least so we can start looking at it. Also I'm available for the Skype asap

**Comment by marc-hanheide** [comment]
yes, a PR is always good to channel the discussion

**Comment by Jailander** [comment]
OK, will do in a minute

**Comment by Jailander** [comment]
BTW meeting is at 3 p.m. If you want to join @marc-hanheide

**Comment by Jailander** [comment]
@bfalacerda new definitions are here https://github.com/Jailander/strands_navigation/tree/hydro-devel/strands_navigation_msgs/msg just one question before I make the PR in NavRoute I switched the target node for the edge_id on the policies is this a big problem? or do you want me to leave it back to source, target, edge_id as we talked before? I wanted to test the policy executor before I make the PR

**Comment by bfalacerda** [comment]
no problem, and it makes sense, as we want to be able to choose from different continuous nav configurations between certain nodes, so providing the target is not enough.

 I don't see that done in 
https://github.com/Jailander/strands_navigation/blob/hydro-devel/strands_navigation_msgs/msg/NavRoute.msg
though

the mdp stuff needs to be updated to handle it though

**Comment by Jailander** [comment]
oops not, commited yet

**Comment by Jailander** [comment]
Sorry bruno, I didn't notice sent you the wrong link anyway, the messages are in https://github.com/Jailander/strands_navigation/blob/indigo-devel/strands_navigation_msgs/msg (wrong branch sorry)

**Comment by hawesie** [comment]
Is it possible to also get some unit tests written for the topological navigation and localisation parts? We rely on them a lot in the system, so having something that runs all (or at least some of) this python code before we do merges would make be feel a lot happier.

**Comment by marc-hanheide** [comment]
Fully agreed, I'll liaise with @Jailander on the issue later today.

**Comment by Jailander** [comment]
Sure I've never written one but I would also feel more comfortable if things are automatically tested before merge.
Looking at https://github.com/strands-project/mongodb_store/blob/hydro-devel/mongodb_store/tests/test_messagestore.py I'd say its not so hard.

**Comment by marc-hanheide** [comment]
An easy way is just to create a launch file which is a standard autonomous one and then check for topics using http://wiki.ros.org/rostest/Nodes
That at least sanity checks that all the component start and that the topics are existing. This requires not even any specific code to be written, just a launch file including the simple test. This should be the defualt for everybody as this catches errors like packages not being found in python etc.

**Comment by hawesie** [comment]
How are the tests?

**Comment by Jailander** [comment]
Fine, most things seem to be ok, 
I'll ping @bfalacerda to have this tested there tomorrow, sorry it took a while, how ever one last question are we doing something about this in the end?

https://github.com/strands-project/strands_movebase/issues/42

**Comment by bfalacerda** [comment]
closing old issues
