### ISSUE TITLE
recovery behaviour to change goal that is NOT in an obstacle

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#187]
re-use code from carrot_planner (see https://github.com/ros-planning/navigation/blob/c264676e954629d86ecb64de0da94a4e46c430d2/carrot_planner/src/carrot_planner.cpp#L151) to make change to a goal close to the obstacle that is one the line between our current pose and the actual goal, hoping we get close enough.

**Comment by bfalacerda** [comment]
This sounded like a good idea at the time, but I'm unsure of how to do really do it, e.g., how do we figure out if we should try using the carrot_planner? @marc-hanheide @cdondrup @Jailander @hawesie , can you describe how you envision this recovery being played out?

**Comment by Jailander** [comment]
I think that if we manage to create a monitor that detects when to goals pose its blocked (an obstacle in that exact pose), then you can get a new goal pose using the carrot planner and use move_base (or any action server) to go to it. That is what I had in mind, haven't seen what might be the problems with that.

**Comment by marc-hanheide** [comment]
yes, the idea was not to really use the carrot planner, but to just use it (or something similar) to find a new goal pose

**Comment by bfalacerda** [comment]
I'll be looking into this now, as I think I've cleared all my other tasks, but I expect it o take time, i.e., having it before the feature freeze might be an issue

**Comment by bfalacerda** [comment]
well, I really dont know how we managed not to see this for so much time but, from the base_global_planner documentation:

~<name>/default_tolerance (double, default: 0.0)
A tolerance on the goal point for the planner. The planner will attempt to create a plan that is as close to the specified goal as possible but no further than default_tolerance away.

I just tested this and it works exactly as we want it to, so during execution of topological navigation, we just need to check if the next waypoint is the final goal, and if not set this param to some value obtained from the node influence area

**Comment by Jailander** [comment]
wow!!! that is great I will add it then

**Comment by bfalacerda** [comment]
great!

Here's the param: `/move_base/NavfnROS/default_tolerance`

You need to set it using rospy.set_param, its not a dynamic reconfigure thingy

**Comment by Jailander** [comment]
Ok awesome I'll add it to my next PR

**Comment by marc-hanheide** [comment]
Problem? See https://github.com/ros-planning/navigation/blob/jade-devel/navfn/src/navfn_ros.cpp#L78... 

This parameter is only read on creation of NavFn. Will that work then?

**Comment by marc-hanheide** [comment]
Also beware: https://github.com/ros-planning/navigation/blob/b2a83c305291e2513713a514f21bf328e7396050/navfn/src/navfn_ros.cpp#L296

Looks to me as if this is _not_ Euclidean distance, but effectively an L\inf norm...

**Comment by Jailander** [comment]
Yes @marc-hanheide is right, I will check if it is possible to have big tolerance on the global palnner and maybe the local planner taking the robot to the goal. not too sure about this

**Comment by bfalacerda** [comment]
the L_\inf norm shouldn't be a problem, we can find the vertices of the influence are that are closer to the waypoint in x and y, and use those to define the square.

Regarding it just being used when NavFn is created, that is really annoying, but it can be fixed easily by adding:

```
ros::NodeHandle nh("~/NavfnROS");
nh.param("default_tolerance", default_tolerance_, 0.0);
```

[here](https://github.com/ros-planning/navigation/blob/indigo-devel/navfn/src/navfn_ros.cpp#L93) and [here](https://github.com/ros-planning/navigation/blob/indigo-devel/navfn/src/navfn_ros.cpp#L194). (Note that I'm useless in cpp so I had to hard code the NavfnROS namespace to the string...). I tested and it works nicely.

I like this solution because it doesnt require extra nodes looking at costmaps, or sending new goals to move_base, everything is solved in move_base itself. The main problem is getting such a thing merged upstream, the move_base guys are extremely slow at getting new stuff in. 

We had our own fork for a while, but I don't know if that would work  with the released system. So I propose sending a PR upstream, and meanwhile add a strands_navfn package to strands_movebase that has this update so we can start using it immediately.

**Comment by bfalacerda** [comment]
The L_\inf comment is wrong, good thing I did a math degree :)

Anyway, i think that wont be a big issue in our implementation, most of the waypoints are octagons anyway, so the comment more or less applies

**Comment by marc-hanheide** [comment]
L_\inf is wrong? My maths knowledge is limited... But what is it then?

**Comment by bfalacerda** [comment]
_My_ L_\inf comment about it not being a problem. For some influence areas it might be, but for the ones we generally use it should be ok

**Comment by Jailander** [comment]
following up the discussion in #227 I agree with removing the tolerances from the definition, but I don't know if changing the topological map definition so close to the deployment is a good idea, I think we can leave it for after the deployment do you agree @bfalacerda?

In such case what we can do is for now using the default xy_tolerance already in the node definition  
to set  `/move_base/NavfnROS/default_tolerance` also the yaw tolerance can be left as 2*PI in between move base actions and have the default value for the final goal and for when edges are not move_base type. sounds good?

**Comment by bfalacerda** [comment]
yes, that would be a nice addition. we're having problems with rotating in place next to doors that should disappear with the yaw_tolerance. could you add please?

**Comment by bfalacerda** [comment]
changing yaw tolerance makes dwa report success immediately after reaching the (x,y) goal. We could have it more that the current default for intermediary waypoints, but i think something like 30º is better,  to make sure that when the next action is not a move_base action the robot is already facing the goal

**Comment by Jailander** [comment]
Ok Sounds good I'm on it

**Comment by bfalacerda** [comment]
please also change the default xy (to be used as goal_tolerance for now) of a topological node to  0.48

**Comment by Jailander** [comment]
Ok I can do that but it will mean running a script or a mongodb query to update older maps

**Comment by bfalacerda** [comment]
migrate.py magic ;)

**Comment by Jailander** [comment]
hahaha yes :)

**Comment by Jailander** [comment]
@bfalacerda close? finally?!?!

**Comment by bfalacerda** [comment]
yes! :)
