### ISSUE TITLE
write service for fremen based prediction of edge durations

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#189]
```
int64 epoch

---
string[] edge_ids
float64[] probs
float64[] durations
```

**Comment by bfalacerda** [comment]
needed soon as the i cant release my stuff without it

**Comment by Jailander** [comment]
@gestom pinging you in here

**Comment by gestom** [comment]
@bfalacerda : Aren't you using the FreNaP ? Technically, it can provide the edge durations.

**Comment by bfalacerda** [comment]
yes, the issue is that when there's no data available for a given edge, it would be good to have a distance based duration. So I was thinking of interacting only with topological navigation, and let it do the interaction with Frenap. It's just adding a service there. The main thing is making sure that I can get predictions for all edges, that's it.

**Comment by gestom** [comment]
Currently, the FreNap would return 0.5s for an unknown edge. This was supposed to faciliate the exploration of unknown edges. I would leave it there, since we could show that the robot is able to learn from experience.

**Comment by Jailander** [comment]
#207 and #205 provide a solution for this, can be called like this for example `rosservice call /topological_prediction/predict_edges "epoch: 1427426324"`.

Missing bits, right now its not adaptive, the model is always order 2 this can be solved using the evaluate action, will be done ASAP.

Second missing bit times are being estimated not predicted, fir the estimation has to be improved, and second when a fremenserver for real numbers is available it should be used here
