### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#198]
given the increasing complexity, this repo needs proper unit tests. In particular to check
- loading and storing of maps on db
- the route planning in the topological map
- the interaction with monitored nav
- others ;-)

**Comment by marc-hanheide** [comment]
I want reemphasise the relevance of this: @Jailander I think we _really_ need unit tests to be implemented for strands_navigation. (@hawesie agrees, I know). There are so many pull requests and tricky bugs and often regressions, that need testing. Can I urge you to implement at least basic run test, as e.g. in https://github.com/strands-project/strands_ui/tree/hydro-devel/pygame_managed_player. In particular, strands_navigation can be very well tested in simulation automatically, and we should do this.

In general, we shall be adopting a policy of not accepting pull requests for repos that don't have at least basic unit tests. I'm happy to help writing them.

**Comment by Jailander** [comment]
Given that there are many new features being being also urgent for the deployment this has been pushed down on my queue will sort out when other prioritary stuff and bugs have been sorted

**Comment by marc-hanheide** [comment]
The thing is that I believe it would help with those bugs and regressions. It's not that tests are an end in itself. They would help you discover bugs _before_ other people find them when running the system. Usually, tests should be the first thing to implement _before_ functionality is in place. So in a way, when a new bug is found, first write a test to reproduce the bug and then fix the bug, making the test pass.

**Comment by Jailander** [comment]
I think I am getting pretty quick bug feedback already ;)

**Comment by Jailander** [comment]
no seriously I just haven't had time to do it, I'll do it as soon as I can focus on it

**Comment by hawesie** [comment]
I second @marc-hanheide's stance: only by having tests will you discover the bugs that are potentially introduced when fixing other things. Given the importance of the nav systems to the project, we can't afford mistakes here.

**Comment by Jailander** [comment]
can we consider this done since #277 ?

**Comment by marc-hanheide** [comment]
I think we can partially ;-) Although you want add tests for the various tools of topological nav.

**Comment by Jailander** [comment]
In the current tests we test loading maps, the map publisher, topological navigation and policy execution. I think the almost all the most important tools are covered, I do think that we need tests in strands_executive testing components that are here like topological prediction. However we can open new more specific issues for the new tests we need which will be easier to track than in this issue.

**Comment by marc-hanheide** [comment]
i thought about all the command line tools you created in utils.

**Comment by Jailander** [comment]
I was actually thinking about deleting many of them since we have services on the map manager doing the same for some and others should not be used any longer, load yaml map is being tested already I could create a test for exporting maps. but I don't think we need more tests apart from that.

**Comment by Jailander** [comment]
we could test the map manger services that's true, but then as I said it would be better to open an issue for creating those specific tests. than having a nine month old issue with a generic name, don't you think?

**Comment by marc-hanheide** [comment]
OK, please do so.
