### ISSUE TITLE
[topological_navigation] Monitored navigation goal is not cancelled when topo goal is

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_navigation#200]
If the topological navigation is cancelled the [preempt callback](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/navigation.py#L171-L177) is called (tested with a simple print) but it does not seem to cancel monitored navigation correctly. The robot is still driving to the last intermediate node before topping.

@Jailander and @bfalacerda is there something wrong, or is it on my end?

**Comment by Jailander** [comment]
I guess you mean stopping ;-)

**Comment by Jailander** [comment]
@bfalacerda I am cancelling monitored navigation goals here: https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/navigation.py#L176 am I missing something?

**Comment by cdondrup** [comment]
As I explained to @Jailander already, this might also be caused by me being mean to my action server. I have a callback listening to the key card of the therapist in the walking group. Whenever the card is shown, it cancels the topo nav goal. I publish this on a latched topic, therefore immediately after sending the goal it is cancelled. I do wait until it is not pending anymore because you cannot cancel a pending goal. This might also be the reason for this:
If a goal is sent and then cancelled immediately after, while it is still pending, the cancel has no effect and you lose any chance on cancelling it again. The goal will just be executed. It takes up to 0.5 seconds for a goal to be not pending any more. Saying 'not pending' because checking for `ACTIVE` does not help, one has to wait for `not PENDING`.

**Comment by bfalacerda** [comment]
There is some extra logic in the preemption mechanism of monitored nav to allow to execute new goals without explicitly cancelling the one being executed. This is done to avoid having the robot stopping and restarting when a goal is overwritten. There might be something working badly there, but I haven't seen it while testing, and I did try to cancel goals very fast and stuff like that . Can you tell me how to replicate the issue @cdondrup ?

**Comment by bfalacerda** [comment]
as this been seen lately?

**Comment by cdondrup** [comment]
Have there been any changes to the preemption lately?

**Comment by bfalacerda** [comment]
nop :p

**Comment by cdondrup** [comment]
Then it should still be an issue ;)

**Comment by bfalacerda** [comment]
well, i dont know how to replicate it

**Comment by cdondrup** [comment]
I'll observe it and see if I can replicate it again.

**Comment by Jailander** [comment]
@cdondrup Can I close this? or did you manage to replicate I lost track of this

**Comment by cdondrup** [comment]
I'll re-open if necessary.
