### ISSUE TITLE
edge_id='' for edges between 'Station' and 'ChargingPoint'

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#211]
We created a topological map from the [basic one](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_utils/support/empty.tmap), and the edge_ids for the docking and undocking actions were empty. That might create some issues if there's stuff assuming different edge_ids for all edges

**Comment by Jailander** [comment]
hmm Ok, I'll check this, it shouldn't be a problem id's can be repeated, however that should be named.

**Comment by Jailander** [comment]
Did you insert it directly using insert_map or did you create a YAML and then insert the yaml?

**Comment by Jailander** [comment]
Ok, I think the problem is in migrate.py, this causes problems when more than one edge per node have empty edges ids as this means that the the robot can't distinguish which edge it should choose

**Comment by bfalacerda** [comment]
sorry, i missed the previous question. I dont think i did any migrate, I think i used the text (non yaml) based insert, though I'm not 100% sure, I tried a lot of things before getting something into mongo

**Comment by Jailander** [comment]
That is a good clue, in any case I'm making the migrate script to also check for empty edge names and assign them. so running the migrate script should fix this (when I'm done)

**Comment by Jailander** [comment]
#209 should fix this, reopen if seen again
