### ISSUE TITLE
Topological navigation fails if no route in map

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_navigation#265]
When there is no path from the current node to the destination node, topological navigation drives the robot to a different node, or otherwise behaves strangely. Instead it should print out a warning and not move the robot anywhere..

This occurred when I had tow areas linked by an edge, but not a return edge. Navigating back to the first area showed this problem so it might not happen if the areas were not at all connected (have not tried).

**Comment by Jailander** [comment]
Just to make sure did this happen with the mdp planner or using the topological navigation action server?

**Comment by cburbridge** [comment]
Without MDP, both when clicking the GoTo marker in RViz and using the topological_navigation/nav_client script.

**Comment by Jailander** [comment]
Ok I'll fix it when I'm back
