### ISSUE TITLE
Try different glocal planner

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#268]
http://wiki.ros.org/global_planner
by recommendation of @cdondrup

**Comment by cdondrup** [comment]
I am currently also working with a version of: https://github.com/strands-project/plugin_local_planner which is DWA made more modular while preserving the previous functionality, meaning: all the critic functions (the ones assigning costs to the sampled trajectories) are now plugins, which means it is quite straight forward to create your own cost function for the local planner and to assign weights to the different costing mechanisms.

**Comment by Jailander** [comment]
Oops just noticed the tittle, but yes following @cdondrup 's comment it seems appropiate now

**Comment by Jailander** [comment]
we decided not to do it
