### ISSUE TITLE
racing condition in execute_policy_server __init__

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#269]
in [execute_policy_server.py#L116](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L116) you are getting the list of all navigation services. This assumes that the services are already there. If `move_base` is not there yet, the call to reconfigure it fails with an [exception](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L611).

The proper solution is a lazy init on the reconf clients and if they have not yet been found in the services, search for them and only throw exception when they cannot be found then.

This racing condition shows up, because we are starting nav2d and mdp nav in one launch file. A work around would be to start nav2d separately first (not a solution!).

**Comment by cdondrup** [comment]
Another problem with that bit of code, [execute_policy_server.py#L119](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L119) is a good approach of dealing with dynamic reconfigure not being there but if the timeout is reached, `config` is empty and therefore [execute_policy_server.py#L125](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L125) crashes the server.

I will include a try except setting it to an arbitrary default value of 0.1 taken from the default params for my tests to work. This still has to be fixed.

**Comment by cdondrup** [comment]
Having solved that, of course [execute_policy_server.py#L612](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py#L612) because there is no client.

**Comment by cdondrup** [comment]
OK, forget all I wrote above, what @marc-hanheide said seems to be the actual cause of the problem.

**Comment by Jailander** [comment]
This is solved I'll close

**Comment by cdondrup** [comment]
Being a bit anal about this, I have to say that waiting for a fixed amount of time is not really a fix for a racing condition ;)

But it seems to work for now.

**Comment by Jailander** [comment]
You can reopen if you want but will go to the bottom of the todo pile

**Comment by Jailander** [comment]
I'm opening a new issue since after the waiting this problem is no longer a racing condition

**Comment by marc-hanheide** [comment]
No, true. I can't be called racing anymore, more a crawling condition with the wait :-P
