### ISSUE TITLE
Visualise topological map

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#27]
It would be good to have a visualisation script for topological nodes and edge.

**Comment by hawesie** [comment]
@Jailander what's the status of this? @BFALacerda would like some quick way of seeing the nodes in rviz. It should be simple enough to copy the waypoint visualiser to make this work.

**Comment by Jailander** [comment]
Hi I haven't paid much attention to it lately, but I will take a look and have it working before integration camp

**Comment by hawesie** [comment]
I think the rviz node-only (no edges) solution would take me about an hour to implement. I can do that today if you want.

**Comment by Jailander** [comment]
Hi Nick, I am doing exactly that right now, don't worry about it, I will have it ready soon. Thank you very much anyway

**Comment by Jailander** [comment]
Hi there is a pull request for the rviz visualization you can view the markers by running 
`rosrun topological_utils visualise_map.py [name of the pointset]` 
I am working on drawing the edges too, that should be ready soon.
