### ISSUE TITLE
Topological navigation indefinitely retries to reach the target waypoint if the robot is already in the influence area

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_navigation#281]
If the robot arrives in the influence area of the target waypoint but cannot reach the goal precisely, it keeps retrying indefinitely. This results in a quite pushy robot and an infinite loop.

**Comment by cdondrup** [comment]
I tested this with the changes made in #282 and the problem seems to be solved. The pushy robot on the end point should now be no more. Has not been tested on the real robot yet, but I think this issue can be closed.

**Comment by Jailander** [comment]
yes I tested it too yesterday seems to work better is still a bit pushi because of move_base but that is what tests are for. I'll close reopen if the behaviour is reobserved.
