### ISSUE TITLE
[topological_utils/node_metadata.py] requires `map_name`

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#295]
Current the query for node meta data requires to set a map_name in the query string. However, the current map is not known to the user...
Either it 
- [x] should be removed from the query and just the topo name being used (which would make sense in my view), and/or
- [ ] it should be left empty when the current map is used (same for the topo map name, actually), and/or
- [ ] the current gridmap name should be published or set as a rosparam (least favourable) by topo-nav, maybe

Whatever you choose, I want this to get rid of the hardcoded name in https://github.com/strands-project/strands_hri/blob/hydro-devel/bellbot_gui/scripts/server.py#L121

**Comment by Jailander** [comment]
yes I think the map name in that query makes no sense I'll remove asap.

**Comment by Jailander** [comment]
can we close this? I think its fixed now
