### ISSUE TITLE
Localise by topic makes the robot think it is at the wrong waypoint

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#298]
We had this issue at the deployment:
"the robot detected that it was charging although it was at WayPoint15, this meant that topological localisation changed current_node to ChargingStation and the battery was too low so the robot's tasks were being set at the ChargingStation which is where it "was" so the robot didn't move, this was fixed by pushing the robot."

Must be Fixed!!!

**Comment by cdondrup** [comment]
I remember we had that last year as well. Is there maybe a way of combining localise by topic and by pose? Only if both are correct it localised at that point. This would also help me for the walking group resting areas.

**Comment by Jailander** [comment]
Yes it was exactly the same issue I'll put a fix in by tomorrow I know I had something almost ready sonewhere

**Comment by cdondrup** [comment]
If my suggestion would also be possible, I'd be grateful ;)

**Comment by Jailander** [comment]
Yes, I think that was one option that was configurable I'll make it possible anyway

**Comment by Jailander** [comment]
This was already fixed last year see: https://github.com/strands-project/strands_navigation/tree/indigo-devel/topological_navigation#using-localise-by-topic

**Comment by Jailander** [comment]
I will close as this is not an issue in the system anymore and its improvement is a duplicate of #249
