### ISSUE TITLE
tests need move_base but it's not a dependency?

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#314]
maybe general run_depend is missing? 

https://lcas.lincoln.ac.uk/jenkins/job/devel-indigo-strands_navigation/41/console

**Comment by hawesie** [comment]
A quick fix would be good as I'd really like the recent updates to these packages released asap, and by the end of Wednesday at the latest as we're using them at a summer school on Thursday.

**Comment by Jailander** [comment]
Move base is a dependency here https://github.com/strands-project/strands_navigation/blob/indigo-devel/monitored_navigation/package.xml#L68 perhaps, we need the more general `move_base` run dependency in topological navigation?
Which is needed as it needs to dynamically reconfigure move_base. I'll add it anyway, but it might not be the cause for this issue.

**Comment by marc-hanheide** [comment]
I guess they have internally changed some deps in `move_base`, which is why now `movebase_state_service` probably doesn't pull in anymore all the stuff we'd need.

**Comment by Jailander** [comment]
move_base is now a run dependency in topological navigation https://github.com/strands-project/strands_navigation/pull/315

**Comment by marc-hanheide** [comment]
Merged but needs re-release
