### ISSUE TITLE
Preempting and aborting actions via topological/monitored navigation

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#34]
I'm just trying to work out how to make the complete task system robust to errors and changes in demands on the robot. 

So, some questions:
- [x] @Jailander will the topological navigation action server ever abort? If so, under want conditions?
- [x] @Jailander will the topological navigation action server respond to preemption from the client (i.e. the task executor)?
- [x] @BFALacerda same questions really: will the monitored navigation ever abort, under what conditions?
- [x] @BFALacerda ca the monitored navigation be preempted?

**Comment by bfalacerda** [comment]
monitored_navigation will abort (outputting failure) after a given number of failures in recovery of either the continuous navigation, or the bumper. These are reconfigurable parameters of the action server.

It should always be preemptable. The only case where there might be a problem is if the continuous navigation action server itself  is not preemptable, as monitored_navigation tries to preempt it during its own preemption.

**Comment by Jailander** [comment]
The topological_navigation aborts when monitored navigation aborts, if preempted it will cancel the monitored_navigation goal.

**Comment by hawesie** [comment]
All ticked.
