### ISSUE TITLE
test small width doors

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#35]
G4S doors are 75cm +/- 1cm. We need to test if the robot is able to navigate through this width using the current navigation

**Comment by bfalacerda** [comment]
@gestom 's door nav solves this. I can't find the .action file for it though, where is it? Shouldn't it be in https://github.com/strands-project/scitos_apps/tree/hydro-devel/scitos_apps_msgs/action?

**Comment by gestom** [comment]
As requested, the door navigation uses MoveBaseAction.

**Comment by bfalacerda** [comment]
ah yeah,sorry...
