### ISSUE TITLE
Change node influence area to be a polygon

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#4]
For more flexibility and integration with other behaviours. 

I believe @kunzel has some code for checking whether a robot pose is within a polygon which can be used for this.

**Comment by Jailander** [comment]
Hi, this is not a problem, I am currently working on it, I will commit it this afternoon. 
This will modify the TopologicalNode definition so issue #3 should wait until this is done.

**Comment by Jailander** [comment]
Hi, sorry for the delay, this is done right now, the only issue is that the polygons have to be convex and the corners given in a way that they are consecutive, in the future probably we can use 
http://toblerity.org/shapely/index.html that does this automaticaly in a more reliable way, but I don't think it is worth adding more requirements to the system just for this.

**Comment by hawesie** [comment]
This now appears to be done, reopen if not.
