### ISSUE TITLE
Topological edges to unknown nodes

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_navigation#59]
If someone would rename nodes in the topological map txt file and misspelled one of the nodes while defining the edges, at least the visualiser will just pick a random node to draw an edge to.
E.g.:

```
node:
         MyWayPoint1
         ...
         edges:
                 WrongNodeName, move_base
```

Where `WrongNodeName` does not exist. It instead just connects to another one. I did not test that for the actual topological navigation but maybe an error output would be nice if there is an edge to an undefined node.

**Comment by Jailander** [comment]
Ok, I will try to fix this as soon as possible

**Comment by hawesie** [comment]
Is this fixed?

**Comment by Jailander** [comment]
Yes it is, I will close the issue

**Comment by Jailander** [comment]
Or you do it since I can't close issues (I forgot)
