### ISSUE TITLE
Distance for topological route

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#67]
I'm trying to recreate the distance travelled by the robot at AAF. It looks like we didn't log odom or robot pose so I plan to do it just from the locations of tasks. To do this I need to know the distance between one node and another. I can do this easily by straight line distance, but this ignores intermediate nodes. So, is there code anywhere to report the distance of a multi-node route? @Jailander @BFALacerda

**Comment by Jailander** [comment]
No there isn't anything like that in the topological navigation action server, however, I could create an to request the plan between two nodes, but I don't know if @BFALacerda has it already.

**Comment by bfalacerda** [comment]
i don't think there is. but you have all the topological nav stats in `message_store`, and all of them have a start and end nodes which are connected via an edge, so we can sum the straight line distances for all nav stat entries. That's more accurate because you are summing the real path the robot took

**Comment by Jailander** [comment]
Yes that is true it is a lot better because you will also be able to see where the robot ended if the navigation failed

**Comment by cdondrup** [comment]
@hawesie If I remember correctly I logged the amcl pose. Have a look at the people_tracks collection in the message_store.

**Comment by hawesie** [comment]
Aha! Is it the `geometry_msgs/PoseWithCovarianceStamped` entries?

**Comment by cdondrup** [comment]
Yes, that's it. The other is the location of detected people.

**Comment by cdondrup** [comment]
If you ran the people perception at G4S it should have logged the same.

**Comment by hawesie** [comment]
Superstar. Ok, I don't need distances after all.
