### ISSUE TITLE
Code to collect timing data on topological map

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#7]
Code and documentation of the correct way to do this.

**Comment by Jailander** [comment]
Should be ready soon

**Comment by Jailander** [comment]
Hi, I don't know which is the more desirable way to do it, right now the statistics are being gathered by the topological navigation action server.
As it is right now, when the experimental flag is set to true (if not it will work as it was before adding this mode) when the robot reaches the influence zone of a node that is not the intended target it cancels the navigation and navigates to the waypoint of that node, and the action server returns that the navigation was not successful. In this case it has to be the planner the one that calls the action again so the robot tries to navigate to the originally intended node.
Other possibility could be that this is done within the same action server, in this case the once the navigation could cancel the navigation go to the waypoint and then replan to the original target and launch the process again until the intended target is reached.

Any thought on this @hawesie @BFALacerda

**Comment by bfalacerda** [comment]
For data gathering I prefer the second option, so we don't have to add anything else. How are you deciding which nodes to visit?

**Comment by Jailander** [comment]
I am using the topological patroller we use on Linda, I will fix the topological navigation to work like this, this weekend

**Comment by bfalacerda** [comment]
Is that around here somewhere already? I'm a bit lost with the new repos still.
I kind of misunderstood your question I think, I would prefer to put the decision of what to do after failure at the level of a "data gathering" patroller and not at the level of the topological navigation action server

**Comment by Jailander** [comment]
there is a pull request on the autonomous patrolling repo with a node called topological patroller, but this is very basic, the idea was to make it work with something more elaborate, if you give me until tomorrow I'll get it working with the data gathering and recovery, but you can take a look meanwhile.

**Comment by bfalacerda** [comment]
Cool, I'll probabily look at it Monday and integrate it with the smach stuff so we have a topological navigation action server with monitors and recovery behaviors

**Comment by Jailander** [comment]
Great!

**Comment by Jailander** [comment]
Hi, there is a pull request for the topological patroller in the autonomous patrolling repository, I am not proud of it, but it seems to work fine, I had to go a couple of versions back to fix some issues, I should have them fixed soon, meanwhile you can check this version, the current state machine looks like this:
![topological_patroller](https://f.cloud.github.com/assets/5035967/2263713/24f362de-9e69-11e3-810d-386e15d63973.png)
In case you were planning on doing something different, I am already gathering statistic of the edges in simulation and works fine, as soon as I have all the other issues fixed I will test on Linda

**Comment by Jailander** [comment]
Hi, I have a question regarding the desired behaviour of navigation, right now I am reconfiguring move_base to not care about orientation of the target waypoint when the navigation is cancelled and a new node (not expected) is reached, is this the desired behaviour for the MDP?, or should I leave it as it was? @BFALacerda

**Comment by bfalacerda** [comment]
Just so I'm sure: you're saying that when node_by_node equals true, the topological navigation is cancelled immediately as the influence area of a wrong node is reached. If so, that's good for me.

**Comment by Jailander** [comment]
yes, but that is not my question :), when node_by_node is set to true and the robot reaches the influence area of a wrong node it cancels the navigation and launches a new navigation to the waypoint of that node, the question is that in the version you have right now that second navigation cares for the orientation at the waypoint whilst in the new one that I am working on it doesn't, which of these cases is better for the MDP creation?

**Comment by bfalacerda** [comment]
for data gathering it should always go to a specific pose I think, so that the starting point for the next movement is always the same.

**Comment by Jailander** [comment]
Ok. I will leave it like that
