### ISSUE TITLE
Recovery actions when non-move base actions are being executed

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#73]
Hi, I was wondering if it will be possible to add a recovery action sending the robot to navigate to the WayPoint of the node it is currently in when using Ramp Climb and possibly Door pass, this seems to be one of the biggest problems for linda since she sometimes call these actions not facing the Ramp/Door so she gets stuck

**Comment by bfalacerda** [comment]
monitored navigation doesn't have the notion of waypoints, what we could do is what we discussed in Stockholm, and have monitored navigation always outputting to topological nav after recovery, so that top nav can check where the topological localization and decide what to do next accordingly

**Comment by Jailander** [comment]
yes that is what I meant, sorry I didn't say it more clearly

**Comment by Jailander** [comment]
I think we can close this issue as the new navigation framework will handle this
