### ISSUE TITLE
Making topological navigation navigate to closest node when not at a node

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#74]
Hi, 

I am planning on making topological navigation navigate to closest node when not at a node if there is no problem with it, currently the route is planned from closest node so if the robot is not at a node it will navigate to the next waypoint in the route, this is not a problem when it happens with move_base like actions but with other actions such as ramp behaviour it is a big problem, @BFALacerda @hawesie is this change OK or do you foresee any problem.

**Comment by hawesie** [comment]
I don’t quite follow the first part. When will this be triggered?

**Comment by Jailander** [comment]
When the robot is not inside the influence zone of a node

**Comment by hawesie** [comment]
Ok, this makes sense.

**Comment by Jailander** [comment]
this is already working closing
