### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#78]
For the [release process](https://github.com/strands-project/strands_management/wiki/software-distribution):
- [ ] merge in content from autonomous patrolling
- [x] all topological to be under one package + _msgs if needed anywhere else
- [ ] reduce the number of packages
- [ ] rename the message_store_map_switcher

**Comment by marc-hanheide** [comment]
I just had a look through those packages. Most importantly, it misses install targets for several packages.

Look at https://github.com/strands-project/mongodb_store/blob/hydro-devel/mongodb_store/CMakeLists.txt to get some idea how to also install `launch/` etc (as this is, for instance missing from https://github.com/strands-project/strands_navigation/tree/hydro-devel/monitored_navigation). Other packages miss all install targets, such as https://github.com/strands-project/strands_navigation/blob/hydro-devel/topological_navigation/CMakeLists.txt

I presume @Jailander and @BFALacerda are looking into this. I would like to release this today if by all means possible.

**Comment by bfalacerda** [comment]
ok, ill take care of monitored_navigation

**Comment by hawesie** [comment]
The point above "all topological to be under one package + _msgs if needed anywhere else" is important for me now as I'm adding features that seem to create circular dependencies between the existing packages. Therefore I propose that I merge the `topological_` packages now. Would that be ok? @BFALacerda @Jailander

**Comment by bfalacerda** [comment]
I don't really understand the point. You want to create something like a topological_navigation_msgs package?

**Comment by hawesie** [comment]
Sorry for being unclear. I meant that I propose to collapse `topological_map_manager` `topological_navigation`  and `topological_utils` into a single `topological_navigation` package.

**Comment by bfalacerda** [comment]
The problem I see with that is that the final package will have a lot of scripts, which might make it difficult to manage. @Jailander is the topological man, he should have a better insight on it

**Comment by hawesie** [comment]
I could imagine keeping the utils package separate if necessary and having that depend on the final package, but the map manager doesn't need to be separate IMO.

**Comment by Jailander** [comment]
yes, I don't see any trouble merging  `topological_map_manager` and `topological_navigation` should be a problem, but I think that adding the `topological_utils` part would be annoying given all the scripts that are in there that are used only on specific situations, however I can make sure that the things on `topological_utils` don't generate any dependencies anywhere else

**Comment by Jailander** [comment]
sorry @hawesie was writing it before you posted I see we agree then, I'll do it tonight then

**Comment by hawesie** [comment]
@Jailander i'll do it as I'm making changes in there anyway. You can check my PR later.

**Comment by Jailander** [comment]
Ok @hawesie lets do that then

**Comment by hawesie** [comment]
Can I also move Vertex and Edge into strands_navigation_msgs as I need them in the top_nav package but don't want to introduce a circular dependency.

**Comment by Jailander** [comment]
yes please put them wherever you prefer, how ever what do you need them for in my development branch I am changing the edge message to add an extra field

**Comment by hawesie** [comment]
I am writing some classes to generate test maps. As the maps are added to the database using Edge and Vertex I need to have access to them.

**Comment by Jailander** [comment]
Ok, I'll take a look at your pull request and see if it affects anything but it probably shouldn't

**Comment by hawesie** [comment]
see #99.

**Comment by Jailander** [comment]
Great, looks good I am going to make some changes that may affect your travel_time stuff but if you don't mind I will try it out tomorrow and fix it if it does

**Comment by marc-hanheide** [comment]
I feel that this repo has a lot of deprecated tickets in it, can somebody competent like @bfalacerda @Jailander @nilsbore @gestom and @hawesie please have a look at all those tickets and close the ones that are implemented or invalid, please?

**Comment by bfalacerda** [comment]
shall we close this one also? I think everything is done

**Comment by Jailander** [comment]
I am closing this issue, if needed (I don't think so) reopen
