### ISSUE TITLE
Make strands_navigation robot-indepdent

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#79]
For the release of this repo I would like to make sure it doesn't depend on the scitos hardware and therefore not depend on scitos-specific messages. Current monitored navigation uses the following scitos messages:
- MotorStatus
- EnableMotors
- ResetMotorStop

It also uses the scitos_ptu package to control the PTU for something.

I propose that we/I implement an abstraction layer for the scitos messages or find an existing one. 

Can the PTU part be replaced with the more generic PTU messages?

**Comment by bfalacerda** [comment]
to have monitored_navigation independent from the scitos, I was thinking of having the global monitor_nav state machine being just a skeleton, and  providing a service to add (monitor_state_machine, recover_state_machine) pairs to it. The way they are added to the global state machine is always the same: the monitor runs concurrently with the nav action server and outputs 'invalid' when some event happens (e.g. bumper is pressed), and when that happens the global state machine jumps to the corresponding recover state machine.

Then we can create a scitos specific monitor and recovery behaviours package and move the monitor and recovery states there.

**Comment by bfalacerda** [comment]
@hawesie do you still want to add the abstraction layer or can we close this?

**Comment by hawesie** [comment]
If strands_navigation is robot-independent then we can close this.
