### ISSUE TITLE
previous_positions_service should be moved into this repo?

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#85]
The build fails because this package is not being found, see https://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-strands_navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/1/console

should it be moved here?

**Comment by Jailander** [comment]
I think this is exactly on what @BFALacerda was working on, I think moving it here should solve any issue anyway but I don't know if it will create any other issues maybe @nilsbore knows

**Comment by bfalacerda** [comment]
no, we should remove this dependency from monitored_navigation. I'm in the process of making it scitos independent by creating a repo for the recovery behaviours and leaving monitored_navigation as just a skeleton smach state machine. I'm also going to put @nilsbore 's backtrack action server there. For now, we can just comment the whole backtrack stuff as it's not used anyway. I already have an open pull request for this repo though, so I'm not sure on how to do it...

**Comment by nilsbore** [comment]
I don't see any problems with this and I think this should go into the backtrack_behaviour package as @BFALacerda suggested. I can put that package into the recovery behaviours repo when that is created.

**Comment by bfalacerda** [comment]
this is done
